pipeline{
    agent any
    stages{
        stage('Building'){
            steps{
                sh 'mvn install'
                
            }
        }
        stage('Rename'){
            steps{
                sh 'mv target/*.jar target/app.jar'
                
            }
        }
        stage('execute'){
            steps{
                sh 'java -jar target/app.jar'
            }
        }
        
    }
}